apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v2
  namespace: kube-system
  labels:
    k8s-app: kube-registry-v2
    version: v2
    kubernetes.io/cluster-service: 'true'
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry-v2
    version: v2
  template:
    metadata:
      labels:
        k8s-app: kube-registry-v2
        version: v2
        kubernetes.io/cluster-service: 'true'
    spec:
      containers:
      - name: registry
        image: registry:2.3.1
        env:
#        - name: REGISTRY_LOG_LEVEL
#          value: 'debug'
        - name: REGISTRY_HTTP_HOST
          value: https://acc-reg.your.com
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_DELETE_ENABLED
          value: 'true'
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
      volumes:
      - name: image-store
        awsElasticBlockStore:
          fsType: ext4
          volumeID: vol-0fe511d7
