apiVersion: v1
kind: ReplicationController
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd
    version: v1
spec:
  replicas: 1
  selector:
    k8s-app: fluentd
    version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd
        version: v1
    spec:
      containers:
      - image: gcr.io/google_containers/fluentd-elasticsearch:1.11
        name: fluentd
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        env:
        - name: FLUENTD_ARGS
          value: -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
