kind: Service
apiVersion: v1
metadata:
  name: registry-ssl-proxy
  namespace: kube-system
  labels:
    name: registry
    role: ssl-proxy
    dns: route53
  annotations:
    domainName: 'prod-reg.your.com'
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: ssl-proxy-https
  selector:
    name: registry
    role: ssl-proxy
