apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    name: mongo-express
  template:
    metadata:
      labels:
        name: mongo-express
    spec:
      containers:
      - image: morriz/mongo-express:latest
        name: mongo-express
        imagePullPolicy: Always
        ports:
        - name: mongo-express
          containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo
