apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: influx
    name: influx
  name: influxdb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: influx
  template:
    metadata:
      labels:
        k8s-app: influx
        name: influx
    spec:
      containers:
      - name: influxdb
        image: kubernetes/heapster_influxdb:v0.6
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
        # awsElasticBlockStore:
        #   volumeID: vol-xxx
        #   fsType: ext4
